### ISSUE TITLE
Make sampled data available.

### ISSUE THREAD

**Issue by ysebiat** [sertalpbilal/fpl_optimized#4]
For across season analysis, it would be nice that all sampled data that has been collected be available.

**Comment by sertalpbilal** [comment]
Raw data is available under *webpage* branch, *sample* directory. Perhaps I can add a README file to mention it, or add a link within the webpage?

**Comment by ysebiat** [comment]
Seems a good idea to me. Link within the webpage is better to make it more broadly available.
